### ISSUE TITLE
Ethical consideration of our project

### ISSUE THREAD

**Issue by Lily-alive** [CSC207-UofT/course-project-group_003#260]
As we need to consider the ethical issues for our software, does anyone have any idea on which of the seven principles we have already implemented and what we could do for the future?

**Comment by Cathypei** [comment]
Since our program have clear indications on how to access the information that the user want, and has instructions on what can they access. I think we have achieved the aspect of Principle 4: Perceptible Information.

**Comment by Tseateen** [comment]
Principle 1: Equitable Use
For now, in terms of privacy and usage, users have completed the same functions for users with the same level of authority.
We can implement functions like voice recognition, speech-to-text in the future to assist the disabled. Also, we can integrate multi-language interfaces to assist users with different language backgrounds. In terms of privacy and usage, users have completed the same functions as users with the same level of authority.

**Comment by Tseateen** [comment]
Principle 2: Flexibility in Use
Besides the future implementation of Principle 1, we will provide multiple choices, including but not limited to choosing the speed of voice playback, multi-languages framework. If we are capable of the technology, we hope to include the bioelectrical electronic recognition feature so that everyone can use our design flexibly.

**Comment by Tseateen** [comment]
Principle 3: Simple and Intuitive Use
At present, we are designing the program with features commonly used by a company, which allows us to be consistent with the user expectations of an HR system. 
In the future, we will implement the voice function and the multi-language design to fully meet this principle and accommodate a wide range of literacy and language skills. Meanwhile, we will further provide more guidance and instructions about using our system in the interface to minimize the complexity of using the system for the users.

**Comment by Tseateen** [comment]
Principle 4: Perceptible Information
Languages and pictures can make the information much more perceptible. In the future, after we implement the voice function, we will add more recognition labels, like pictures. Also, we will present the information in different areas with different sizes and colours.

Principle 5: Tolerance for Error
In the future, we will back up all the work files in the system and make a backup to ensure the file will not be lost. In addition, we will save the file immediately when the immediate exit of the user happens to prevent the file from being lost or damaged. The system will also ask and verify the user when the file is to be deleted if the user does this action accidentally. Our system will save the deleted files for a long time so that the user can recover the deleted files. These functions will maximize the tolerance for error.

Principle 6: Low Physical Effort
This principle is not applicable for our design so far because the main functionalities of the HR system are to manage the input information and export the processed data. So it minimizes repetitive actions as well as sustained physical effort. However, we believe that the future implementation of voice recognition and output will allow the user to maintain a neutral body position.

Principle 7: Size and Space for Approach and Use
Like principle 6, this principle is also not applicable to our design so far. However, if we implement more hardware and accessory equipment in the future, this will help with this principle.
